project:
  type: website
  output-dir: _tmp/projr/v0.0.0-1/docs
website:
  title: Your Slide Deck Title
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: SlidesDayOne.qmd
      text: Slides

