project:
  type: website
  render:
  - index.qmd
  output-dir: _tmp/projr/v0.0.1-1/docs
website:
  title: Statistical Computing
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: r.qmd
      text: R and RStudio
    - href: quarto.qmd
      text: Quarto
    - href: git.qmd
      text: Git and GitHub
    - href: markdown.qmd
      text: Markdown
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left

