project:
  type: book
  render:
  - index.qmd
  - r.qmd
  - projects.qmd
  - quarto.qmd
  - git.qmd
  - projrsimple.qmd
  - prac1.qmd
  output-dir: _tmp/projr/v1.0.11/docs
book:
  title: Statistical Computing
  sidebar:
    border: true
    background: light
    position: right
  navbar:
    search: true
    background: light
  chapters:
  - index.qmd
  - r.qmd
  - projects.qmd
  - quarto.qmd
  - git.qmd
  - projrsimple.qmd
  - prac1.qmd
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left

