project:
  type: book
  render:
  - index.qmd
  - day1.qmd
  - r.qmd
  - projects.qmd
  - quarto.qmd
  - git.qmd
  - projrsimple.qmd
  - prac1.qmd
  - day5.qmd
  - tidyverse.qmd
  - prac-day-five.qmd
  - ggplot2.qmd
  output-dir: _tmp/projr/v1.0.33-1/docs
book:
  title: Statistical Computing
  sidebar:
    border: true
    background: light
  navbar:
    search: true
    background: light
  chapters:
  - index.qmd
  - part: day1.qmd
    chapters:
    - rstudio.qmd
    - r.qmd
    - projects.qmd
    - quarto.qmd
    - git.qmd
    - projrsimple.qmd
    - prac1.qmd
  - part: day4.qmd
    chapters:
    - tidyverse.qmd
    - prac-day-four.qmd
    - ggplot2.qmd
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: right

