# Practical Day Five {#sec-day5-prac}

Excellent practice is all of the questions in the [R4DS Data Visualisation introduction](https://r4ds.had.co.nz/data-visualisation.html#data-visualisation), so I suggest you do them (probably skipping the non-coding questions, so as to get through the content faster).

In addition, most (if not all) of Birgit's uploaded questions involve plots, so you can use those as practice too.
They also have the advantage that they will involve learning relevant statistical and mathematical functions.

However, for this practical, here are the questions you will need to answer:

## Question One

1. Simulate 100 random numbers from a normal distribution with mean 3 and standard deviation 1. Use `ggplot2` to plot the empirical density of these, and format the plot according to best practice (e.g. with axis titles, caption, etc.).
2. Make a reference to the plot in the text (e.g. using `@fig-dens-plot`).
3. Overlay the true density of the normal distribution on the plot (hint: use `geom_line`).

## Question Two

Calculate a two-way frequency table of species of penguins and island location (from the `palmerpenguins` package's dataset), and display it according to best practices (e.g. table caption, appropriate lines, etc.).

## Question Three

Plot the distribution of the flipper length of penguins, separated by species. Create three plots:

1. All species in the same plot, using the `geom_boxplot` function.
2. All species in the same plot, and use the `geom_density` function (hint: use the `alpha` parameter to make overlapping densities more visible).
3. Each species in a separate facet.

These plots need not include captions or be referenced in the text, but should follow other best practices.